spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Smart Video
  description: "Play a video from YouTube, Vimeo, or your local files."
  icon: videocam
  tags: []
  preview:
    icon: videocam
    text:
      - template: Smart Video - {video._type}
      - Smart Video
    subtext:
      - key: video.title
      - key: video.source
      - Add video

blueprint:
  video:

preview:

_inputs:
  title:
    type: text
    comment: The video title provides accessibility information for assistive technologies (like screen readers) and can display a tooltip when a user hovers over the video.
  video:
    type: object
    options:
      structures:
        values:
          - label: YouTube
            value:
              _type: youtube
              id:
              title:
            _inputs:
              id:
                type: text
                comment: Enter a video ID from a public video on YouTube.
          - label: Vimeo
            value:
              _type: vimeo
              id:
              title:
            _inputs:
              id:
                type: text
                comment: Enter a video ID from a public video on Vimeo.
          - label: Self Hosted
            value:
              _type: self-hosted
              source:
              poster:
            _inputs:
              source:
                type: file
                label: Video Source
                comment: Must be mp4 as this is supported by all modern browsers.
                options:
                  accepts_mime_types:
                    - video/mp4
                  paths:
                    uploads: public/videos
                    static: public
              poster:
                type: image
                comment: The image displayed before the video plays or while it is loading.
                options:
                  accepts_mime_types:
                    - image/jpeg
                    - image/png
                    - image/webp
                  paths:
                    uploads: public/assets/images
                    static: public
