spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Grid
  description: "Responsive, centered grid with configurable sizing."
  icon: grid_on
  tags: []

blueprint:
  minItemWidth: 200
  maxItemWidth: 320
  verticalAlignment: start
  horizontalAlignment: center
  equalWidth: true
  items: []

preview:

_inputs:
  minItemWidth:
    type: number
    comment: The minimum width for each grid item in pixels.
  maxItemWidth:
    type: number
    comment: The maximum width for each grid item in pixels.
  verticalAlignment:
    type: select
    comment: The vertical alignment of grid items.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
        - id: stretch
          name: Stretch
  horizontalAlignment:
    type: select
    comment: The horizontal alignment of grid items.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
        - id: space-between
          name: Space Between
        - id: space-around
          name: Space Around
        - id: space-evenly
          name: Space Evenly
  equalWidth:
    type: switch
    comment: Whether items should have equal widths (true) or intrinsic widths based on content (false).
  items:
    type: array
    label: Grid Items
    comment: Array of grid items, each containing content blocks to render.
    options:
      structures: _structures.grid_item

_structures:
  grid_item:
    values:
      - value:
          contentBlocks: []
        _inputs:
          contentBlocks:
            type: array
            comment: Content blocks to render within this grid item.
            options:
              structures: _structures.contentBlocks
        preview:
          icon: grid_view