spec:
  structures:
    - formBlocks
  label: Choice Group
  description: "A group of checkboxes or radio buttons with labels."
  icon: rectangle
  tags: []

blueprint:
  name:
  options:
    - value: newsletter
      label: Subscribe to newsletter
      checked: false
    - value: updates
      label: Get product updates
      checked: false
  title:
  orientation: vertical
  required: false
  multiple: true

preview:

_inputs:
  name:
    type: text
    comment: The name attribute for the input group.
  options:
    type: blocks
    comment: Array of choice options with value, label, and checked state.
  title:
    type: text
    comment: Optional title text for the fieldset.
  orientation:
    type: select
    comment: The layout orientation - vertical for stacked layout, horizontal for grid layout.
    options:
      values:
        - vertical
        - horizontal
  required:
    type: switch
    comment: Whether the field is required.
  multiple:
    type: switch
    comment: When true, uses checkboxes for multiple selection. When false, uses radio buttons for single selection.
