spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Accordion
  description: Hides content behind an expandable menu.
  icon: expand_all
  tags:

blueprint:
  items:
  openFirst: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items:
    comment: The items to display in the accordion.
    type: array
    icon: expand_all
  title:
    comment: The title of the accordion item.
    type: text
  openFirst:
    comment: "If true, the first item will be open by default."
    type: checkbox

_structures:
  items:
    values:
      - label: Item
        icon: place_item
        value:
          title:
          contentBlocks:
