spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Button Group
  description: "Controls the alignment and direction of buttons."
  icon: rectangle
  tags: []

blueprint:
  buttonBlocks:
  direction: row
  align: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  buttonBlocks:
    comment: Array of button components to render within the group.
    type: array
  direction:
    comment: Direction of button layout.
    type: select
    options:
      values:
        - row
        - column
  align:
    comment: Alignment of buttons within the group.
    type: select
    options:
      values:
        - start
        - center
        - end
