spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Button Group
  description: "Controls the alignment and direction of buttons."
  icon: rectangle
  tags: []
  preview:
    text: Button Group
    subtext:
      - template: 

blueprint:
  buttonBlocks:
  direction: row
  align: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  buttonBlocks:
    comment: Array of button components to render within the group.
    options:
      structures: _structures.buttonBlocks
  direction:
    type: select
    comment: Direction of button layout.
    options:
      values:
        - id: row
          name: Row
        - id: column
          name: Column
  align:
    type: select
    comment: Alignment of buttons within the group.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
