spec:
  structures:
    - content_blocks
  label: Testimonial
  description: A quote with an author and description
  icon: format_quote
  tags:

blueprint:
  quote:
  authorName:
  authorDescription:
  horizontalAlignment: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  quote:
    type: markdown
    comment: Quotation marks will be added around the text.
    options:
      bold: true
      italic: true
      link: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
  authorDescription:
    type: textarea
  horizontalAlignment:
    type: select
    options:
      values:
        - value: start
          name: Start
        - value: center
          name: Center
        - value: end
          name: End
      value_key: value
      preview:
        text:
          - key: name
