spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Content Selector
  description: Switches between related content panels using tab buttons.
  icon: view_sidebar
  tags:

blueprint:
  items:
  navigationPosition: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  navigationPosition:
    type: select
    options:
      values:
        - start
        - top

_structures:
  items:
    values:
      - label: Item
        icon: place_item
        value:
          title:
          contentBlocks:
