# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Blog Grid
  description: "A responsive blog block that displays an array of blog posts in a grid layout using cards. Each post includes an image, title, excerpt, and date."
  icon: article
  tags: ["blog", "content", "grid", "cards"]

# Defines the structure of this component, as well as the default values
blueprint:
  blogPosts: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  blogPosts:
    type: array
    comment: "Array of blog posts to display in the grid."
    options:
      structures: _structures.blog_post

_structures:
  blog_post:
    values:
      - value:
          title: "Exploring Dunedin's Heritage"
          excerpt: "Discover the rich history and cultural heritage that makes Dunedin one of New Zealand's most fascinating cities."
          date: "2024-01-15"
          imageSource: ""
          imageAlt: "Historic Dunedin building"
          url: "#"
        _inputs:
          title:
            type: text
            comment: "The title of the blog post."
          excerpt:
            type: text
            comment: "A brief excerpt or description of the blog post content."
          date:
            type: date
            comment: "The publication date of the blog post."
          imageSource:
            type: image
            comment: "URL or path to the blog post image."
          imageAlt:
            type: text
            comment: "Alt text for the blog post image for accessibility."
          url:
            type: url
            comment: "The URL link to the full blog post. Leave empty or use '#' for no link."
        preview:
          icon: article
          text:
            - key: title
          subtext:
            - key: date
            - { { date } }
          image:
            - key: imageSource
