spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Divider
  description: A horizontal line to separate content
  icon: horizontal_rule
  tags:

blueprint:
  padding:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  padding:
    comment: The space on the top and bottom of the horizontal line.
    type: select
    options:
      values:
        - name: None
          value: none
        - name: Extra Small
          value: xs
        - name: Small
          value: sm
        - name: Medium
          value: md
        - name: Large
          value: lg
        - name: Extra Large
          value: xl
        - name: 2xl
          value: 2xl
        - name: 3xl
          value: 3xl
