spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Simple Text
  description: "Displays blocks of text for content sections with options for alignment, size and decoration."
  icon: view_headline
  tags: []

blueprint:
  text:
  align: start
  size: md

preview:

_inputs:
  text:
    type: markdown
    comment: The text content of the simple text.
    options:
      bold: true
      italic: true
      link: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
  align:
    type: select
    comment: The alignment of the text.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
  size:
    type: select
    comment: The font size of the text.
    options:
      values:
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
        - id: 4xl
          name: 4xl
        - id: 5xl
          name: 5xl
        - id: 6xl
          name: 6xl
