spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Rich text
  description: A catch all for all content types. Can contain headings, paragraphs, images, bullets.
  icon: edit_note
  tags:

blueprint:
  text:
  align:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    comment: The content for the rich text component.
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      bulletedlist: true
      numberedlist: true
      indent: true
      outdent: true
      join_above: true
      join_below: true
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
  align:
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
    comment: The alignment of the rich text component.
