spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Spacer
  description: Gives space between content
  icon: space_bar
  tags:

blueprint:
  size:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  size:
    comment: The amount of space to add
    type: select
    options:
      values:
        - xs
        - sm
        - md
        - lg
        - xl
        - 2xl
        - 3xl
