spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Smart Image
  description: Displays an image optimized for performance with smart CDN detection.
  icon: image
  tags: []

blueprint:
  src:
  alt:
  rounded: false
  aspectRatio: null
  positionVertical: center
  positionHorizontal: center

preview:

_inputs:
  src:
    type: text
    comment: The URL or path to the image
  alt:
    type: text
    comment: Alternative text for accessibility
  rounded:
    type: switch
    comment: Whether to apply rounded corners to the image
  aspectRatio:
    type: select
    comment: Set a fixed aspect ratio for the image
    options:
      - square
      - landscape
      - portrait
      - widescreen
      - golden
  positionVertical:
    type: select
    comment: Vertical positioning of the image within the container
    options:
      - top
      - center
      - bottom
  positionHorizontal:
    type: select
    comment: Horizontal positioning of the image within the container
    options:
      - left
      - center
      - right
