spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Smart Image
  description: Displays an image optimized for performance with smart CDN detection.
  icon: image
  tags: []
  preview:
    icon: image
    text: Smart Image
    subtext:
      - key: alt
      - key: source  

blueprint:
  source:
  alt:
  rounded: false
  aspectRatio: null
  positionVertical: center
  positionHorizontal: center

preview:

_inputs:
  source:
    type: image
    comment: The URL or path to the image.
  alt:
    type: textarea
    comment: Alternative text for accessibility.
  rounded:
    type: switch
    comment: Whether to apply rounded corners to the image.
  aspectRatio:
    type: select
    comment: Set a fixed aspect ratio for the image.
    options:
      - id: square
        name: Square
      - id: landscape
        name: Landscape
      - id: portrait
        name: Portrait
      - id: widescreen
        name: Widescreen
      - id: golden
        name: Golden
  positionVertical:
    type: select
    comment: Vertical positioning of the image within the container.
    options:
      - id: top
        name: Top
      - id: center
        name: Center
      - id: bottom
        name: Bottom
  positionHorizontal:
    type: select
    comment: Horizontal positioning of the image within the container.
    options:
      - id: left
        name: Left
      - id: center
        name: Center
      - id: right
        name: Right
