spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Carousel
  description: "A carousel component for displaying slides with navigation controls"
  icon: image
  tags: []

blueprint:
  label: ""
  slides: []
  autoPlay: false
  autoScroll: false
  slideWidthPercent: 100
  minSlideWidth: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    type: text
    comment: Optional label for the carousel to help identify it in the editor.
  slides:
    type: array
    comment: Array of slides to display in the carousel.
    options:
      structures: _structures.slide
  autoPlay:
    type: switch
    comment: Enable auto-play functionality.
  autoScroll:
    type: switch
    comment: Enable auto-scroll functionality.
  slideWidthPercent:
    type: range
    comment: Width of each slide as a percentage (e.g., 33, 50, 100).
    min: 0
    max: 100
    step: 1
  minSlideWidth:
    type: number

    comment: Minimum width of slides in pixels. Prevents slides from getting too small.
_structures:
  slide:
    values:
      - value:
          contentBlocks: []
        _inputs:
          contentBlocks:
            type: array
            options:
              structures: _structures.contentBlocks
        preview:
          icon: transition_slide
