spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Rich text
  description: A catch all for all content types. Can contain headings, paragraphs, images, bullets. Use text prop for markdown content or slot for HTML content.
  icon: edit_note
  tags:

blueprint:
  text:
  align:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown
    comment: The content for the rich text component (markdown format). Leave empty to use slot content instead.
    options:
      bold: true
      italic: true
      link: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      redo: true
      format: p h1 h2 h3 h4 h5 h6
      removeformat: true
      copyformatting: true
      bulletedlist: true
      numberedlist: true
      indent: true
      outdent: true
      join_above: true
      join_below: true
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
  align:
    type: select
    comment: The alignment of the rich text component.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
